import { editorTranslate } from '../i18n/editorTranslate';
import type { Language } from '../i18n/translations';
type Props = { language: Language };
export function ImageEditorGuide({ language }: Props) {
 const t = (ko: string, en: string) => editorTranslate(language,ko,en);
 const steps = [
  ['사진 준비하기','Start with a photo','사진 불러오기를 눌러 PNG·JPG·WebP 파일을 선택하세요. 파일당 20MB까지 사용할 수 있습니다. 먼저 둘러보고 싶다면 샘플로 시작을 눌러 보세요.','Choose Open image and select a PNG, JPG or WebP up to 20 MB. Choose Try sample to explore before using your own photo.'],
  ['완성할 이미지 크기 고르기','Choose your output size','왼쪽 프리셋에서 게시할 곳에 맞는 크기를 선택하세요. 직접 가로·세로를 입력해도 됩니다. 완성 이미지 비율 유지를 켜면 한쪽 크기를 바꿀 때 다른 쪽도 함께 조절됩니다.','Choose a preset in the output-size panel, or enter width and height. Enable Lock output aspect ratio to adjust both dimensions together.'],
  ['사진을 원하는 위치에 맞추기','Frame your photo','사진 한 장은 사진 확대·축소로 크기를 조절하고 미리보기에서 드래그해 이동하세요. 사진을 클릭한 뒤 방향키는 1px, Shift+방향키는 10px씩 이동합니다.','For a single photo, use Photo zoom and drag it in the preview. Click the photo, then use arrow keys to move 1 px or Shift + arrows to move 10 px.'],
  ['색감과 장식 더하기','Adjust and decorate','밝기·대비·채도와 필터로 사진 분위기를 바꿔 보세요. 스티커를 누르면 중앙에 추가됩니다. 문구 추가를 누르면 직접 입력할 수 있고, 줄바꿈·굵게·흰색 외곽선도 사용할 수 있습니다.','Adjust brightness, contrast, saturation and filters. Click a sticker to add it in the center. Add text to type your own message with line breaks, bold and a white outline.'],
  ['완성한 이미지 저장하기','Download your image','저장 형식을 선택하고 이미지 다운로드를 누르세요. 미리보기가 작게 보여도 선택한 출력 픽셀 크기로 저장됩니다. 사진·스티커·문구는 한 장의 이미지로 합쳐집니다.','Choose an export format and click Download image. The preview is scaled for your screen, but the selected pixel dimensions are preserved. Photos, stickers and text are combined into one image.'],
 ];
 const faq = [
  ['사진 크기와 완성 이미지 크기는 어떻게 다른가요?','How are photo zoom and output size different?','완성 이미지 크기는 저장되는 파일의 가로·세로입니다. 사진 확대·축소는 그 안에 놓인 사진만 바꿉니다. 예를 들어 1080×1350 프리셋에서 사진을 150%로 확대해도 저장 크기는 1080×1350입니다.','Output size is the width and height of the saved image. Photo zoom only changes the photo inside it. Zooming to 150% in a 1080×1350 preset still exports at 1080×1350.'],
  ['맞춤 방식은 무엇을 선택하면 되나요?','Which fit mode should I choose?','전체 이미지 맞추기는 사진을 모두 보여주고 남는 공간에 여백을 만듭니다. 가득 채워 자르기는 빈 공간 없이 채우는 대신 가장자리가 잘릴 수 있습니다. 단일 사진의 어두운 바깥 영역은 잘리는 부분이고 밝은 테두리 안쪽만 저장됩니다. 콜라주 사진은 각 칸을 채우도록 맞춰집니다.','Fit entire image keeps the whole photo and may add padding. Fill & crop fills the frame but may crop the edges. For a single photo, dark outer areas are cropped and only the area inside the bright border is saved. Collage photos fill their individual cells.'],
  ['스티커 색상이 바뀌지 않아요.','Why can’t I recolor this sticker?','점 표시가 있는 도형·아이콘 스티커는 색상 변경이 가능합니다. 선택한 요소에서 추천 색상을 누르거나 직접 선택하세요. 이모지는 고유 색상을 사용하며 기기에 따라 모양이 다를 수 있습니다.','Shapes and icons marked with a dot can be recolored. Choose a recommended or custom color under Selected element. Emoji retain their original colors and may look different across devices.'],
  ['겹친 스티커나 문구를 선택하고 싶어요.','How do I select overlapping elements?','레이어 목록에서 원하는 항목을 선택하세요. 맨 앞으로·맨 뒤로 버튼으로 순서를 바꾸고 복제·삭제할 수 있습니다. 크기·회전·불투명도는 슬라이더, 숫자 입력, −/＋ 버튼 중 편한 방식으로 조절하세요.','Select the item in the Layers list. Bring it to front, send it to back, duplicate or delete it. Adjust size, rotation and opacity using sliders, numbers or −/+ buttons.'],
  ['사진이 흐릿해 보일 때는 어떻게 하나요?','What if the photo looks blurry?','작은 사진을 크게 늘리면 선명도가 떨어질 수 있습니다. 가능하면 큰 원본을 사용하고 과도한 확대를 줄여 주세요. 불러올 때 긴 변은 단일 사진 최대 2400px, 콜라주 사진 최대 2000px로 조절됩니다. 출력은 각 변 최대 4096px입니다.','Enlarging a small photo can reduce sharpness. Use a larger original and avoid excessive zoom. Imports are limited to a 2400 px longest edge for single photos and 2000 px for collage photos. Output supports up to 4096 px per edge.'],
  ['실수했거나 사진을 다시 배치하고 싶어요.','How can I undo or reset placement?','실행 취소·다시 실행으로 편집을 되돌릴 수 있습니다. 최근 30단계의 변경을 보관합니다. 사진 배치 초기화를 누르면 해당 사진의 확대와 위치가 기준 상태로 돌아갑니다. 사진 보정 초기화는 밝기·대비·채도와 필터를 초기화합니다.','Undo and Redo let you revisit the latest 30 changes. Reset photo placement restores the photo’s base zoom and position. Reset adjustments restores brightness, contrast, saturation and the original filter.'],
 ];
 return <section className="ie-guide-v2" aria-labelledby="editor-guide-title"><header><span className="ie-eyebrow">{t('빠른 시작 가이드','Quick start guide')}</span><h2 id="editor-guide-title">{t('처음이어도 쉽게, 이미지 편집 가이드','Your easy image editing guide')}</h2><p>{t('사진 한 장을 다듬거나 여러 장을 모아 콜라주를 만들어 보세요. 아래 순서대로 따라 하면 됩니다.','Polish one photo or combine several into a collage. Follow the steps below to get started.')}</p></header>
 <div className="ie-guide-steps">{steps.map(([ko,en,bodyKo,bodyEn],i)=><article key={en}><span className="ie-guide-number">{String(i+1).padStart(2,'0')}</span><h3>{t(ko,en)}</h3><p>{t(bodyKo,bodyEn)}</p></article>)}</div>
 <div className="ie-guide-columns"><article className="ie-guide-feature"><h3>{t('여러 장을 한 장으로 · 콜라주 만들기','Combine photos · Make a collage')}</h3><ol><li>{t('상단 콜라주 레이아웃에서 좌우 2분할·상하 2분할·큰 사진 + 2장·4칸 격자를 선택하세요. 기존 사진이 있으면 첫 번째 칸에 들어갑니다.','Choose Side by side, Top and bottom, Featured + two or Four-cell grid in the top toolbar. Your existing photo goes into the first cell.')}</li><li>{t('미리보기의 칸이나 설정의 칸 번호를 선택한 뒤 사진 추가 / 교체를 누르세요. 콜라주에서는 상단 사진 불러오기도 선택한 칸에 사진을 넣습니다.','Select a cell in the preview or its number in settings, then choose Add / replace photo. Open image also adds a photo to the selected cell in collage mode.')}</li><li>{t('각 칸의 사진을 드래그해 맞추고 선택한 사진 확대를 조절하세요. 방향키로도 움직일 수 있습니다. 칸 비우기는 선택한 사진만 제거합니다.','Drag each photo into place and adjust Selected photo zoom. Arrow keys also work. Clear cell removes only the selected photo.')}</li><li>{t('레이아웃을 바꿔도 최대 4칸의 사진은 유지됩니다. 빈 칸에는 선택한 배경 설정이 적용됩니다. 사진 보정은 콜라주 전체 사진에 적용되며, 칸 번호와 선택 테두리는 저장되지 않습니다.','Up to four photos are retained when changing layouts. Empty cells use your background setting. Adjustments affect all collage photos; cell numbers and selection borders are not exported.')}</li></ol></article>
 <article className="ie-guide-feature"><h3>{t('모바일에서는 이렇게 사용하세요','Editing on your phone')}</h3><p>{t('미리보기 아래 설정 영역은 상단의 두 탭으로 열고 접을 수 있습니다.','Use the two settings tabs to expand or collapse the panels below the preview.')}</p><ul><li>{t('사진·크기 설정: 프리셋, 사진 추가·교체, 확대, 배경색, 사진 보정을 설정합니다.','Photo settings: presets, add/replace photos, zoom, background and adjustments.')}</li><li>{t('스티커·문구·저장: 장식을 추가하고 레이어를 편집하거나 이미지를 다운로드합니다.','Stickers, text & export: add decorations, edit layers and download.')}</li><li>{t('사진이나 스티커 위에서 손가락으로 드래그하면 이동합니다. 페이지를 스크롤하려면 미리보기 바깥 영역을 밀어 주세요.','Drag on a photo or sticker to move it. Swipe outside the preview to scroll the page.')}</li><li>{t('미세 조절에는 −/＋ 버튼을 사용하세요. 열려 있는 탭을 다시 누르면 설정이 접혀 이미지를 보기 편해집니다.','Use −/+ for fine adjustments. Tap the active tab again to hide its panel.')}</li></ul></article></div>
 <article className="ie-guide-formats"><h3>{t('어떤 형식으로 저장할까요?','Which download format should I use?')}</h3><div>{[['PNG','투명 배경·문구·그래픽','Transparency, text & graphics','투명 배경을 유지하거나 선명한 장식을 저장할 때 선택하세요.','Choose for transparency and crisp graphics.'],['JPG','사진 공유·용량 조절','Photo sharing & file size','품질을 낮추면 용량을 줄일 수 있습니다. 투명 영역은 선택한 배경색으로 채워집니다.','Lower quality to reduce size. Transparent areas use the selected background color.'],['WebP','투명 배경과 압축','Transparency & compression','투명도를 유지하면서 용량을 조절할 수 있습니다. 게시할 서비스의 지원 여부를 확인하세요.','Supports transparency and adjustable compression. Check your destination supports it.']].map(([name,ko,en,bk,be])=><section key={name}><strong>{name}</strong><h4>{t(ko,en)}</h4><p>{t(bk,be)}</p></section>)}</div></article>
 <div className="ie-guide-save"><strong>{t('작업을 마치기 전에 꼭 다운로드하세요','Download before leaving')}</strong><p>{t('사진은 현재 브라우저에서 처리되며 서버에 업로드·저장되지 않습니다. 편집 내용은 자동 저장되지 않습니다. 새로고침하거나 페이지를 닫으면 작업이 사라집니다. 단일 사진 모드에서 새 사진을 불러오거나 샘플로 시작하면 기존 편집이 초기화됩니다.','Photos are processed in your browser without uploading or server storage. Edits are not autosaved and are lost on refresh or closing the page. Opening another photo in single-photo mode, or starting the sample, resets existing edits.')}</p></div>
 <div className="ie-guide-faq"><h3>{t('궁금한 점을 빠르게 확인하세요','Quick answers')}</h3>{faq.map(([ko,en,bk,be])=><details key={en}><summary>{t(ko,en)}</summary><p>{t(bk,be)}</p></details>)}</div></section>;
}
