import { track } from '../utils/analytics';
import { ClockFace, DurationFace, ClockDisplay, clockSkins, validClockSkin, type ClockSkin } from '../components/clock/ClockFace';
import { AdSlot } from '../components/AdSlot';
import { worldGuide } from '../i18n/worldGuide';
import { focusWindow, localDateInput } from '../utils/focusTime';
import type { CSSProperties } from 'react';
import { useWorldSeo } from '../utils/useWorldSeo';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Maximize, Minimize, Bell, Settings, Sun, Moon, X } from 'lucide-react';
import { Header } from '../components/Header';
import { useLanguage } from '../i18n/LanguageContext';
import { worldText } from '../i18n/worldText';
import { cityZones, duration, isDaytime, nextAlarm, validZone, type Alarm } from '../utils/worldTime';
import './WorldClock.css';

const localZone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
function read(key: string): unknown { try { return JSON.parse(localStorage.getItem(key) || 'null'); } catch { return null; } }
function initialZones() { const saved=read('qk-clock-zones'); return Array.isArray(saved)&&saved.length?saved.filter((z):z is string=>typeof z==='string'&&validZone(z)).slice(0,8):Array.from(new Set([localZone,'America/New_York','Europe/London','Asia/Tokyo'])); }
function initialAlarms(): Alarm[] { const saved=read('qk-clock-alarms'); if(!Array.isArray(saved))return []; return saved.filter(a=>a&&typeof a.id==='string'&&typeof a.name==='string'&&typeof a.time==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time)&&typeof a.zone==='string'&&validZone(a.zone)&&typeof a.next==='number'&&typeof a.enabled==='boolean').slice(0,12).map(a=>({...a,days:[],next:a.next<Date.now()?nextAlarm(a.time,a.zone,[],Date.now()):a.next})); }
export default function WorldClockPage(){
  const {language,t}=useLanguage(), s=worldText[language], navigate=useNavigate();
  useWorldSeo(language);
  const guide = worldGuide[language];
  const locale={ko:'ko-KR',en:'en-US',ja:'ja-JP',zh:'zh-CN',es:'es-ES'}[language];
  const [zones,setZones]=useState(initialZones); const [main,setMain]=useState(()=>{const v=read('qk-clock-main');return typeof v==='string'&&validZone(v)?v:localZone;});
  const [now,setNow]=useState(Date.now()); const [mode,setMode]=useState<'clock'|'stopwatch'|'timer'|'focus'>('clock');
  const [h24,setH24]=useState(()=>read('qk-clock-24')!==false); const [seconds,setSeconds]=useState(()=>read('qk-clock-seconds')!==false);
  const [skin,setSkin]=useState<ClockSkin>(()=>{const value=read('qk-clock-skin');return validClockSkin(value)?value:'default';});
  const [search,setSearch]=useState(''); const [choice,setChoice]=useState('Asia/Seoul');
  const [alarms,setAlarms]=useState<Alarm[]>(initialAlarms); const [alarmName,setAlarmName]=useState(''); const [alarmTime,setAlarmTime]=useState('09:00');const [alarmZone,setAlarmZone]=useState(localZone);const [tone,setTone]=useState('soft');
  const [alerts,setAlerts]=useState<{id:string;name:string;tone:string}[]>([]);const [snoozes,setSnoozes]=useState<{id:string;name:string;tone:string;at:number}[]>([]);
  const [swStart,setSwStart]=useState<number|null>(null);const [swTotal,setSwTotal]=useState(0);const [laps,setLaps]=useState<number[]>([]);
  const [minutes,setMinutes]=useState(25);const [remaining,setRemaining]=useState(25*60000);const [deadline,setDeadline]=useState<number|null>(null);
  const [background,setBackground]=useState(()=>{const saved=read('qk-clock-background');return typeof saved==='string'&&/^#[0-9a-f]{6}$/i.test(saved)?saved:'#0d1423';});
  const [focusDate,setFocusDate]=useState(()=>localDateInput(Date.now()));const [focusStart,setFocusStart]=useState('09:00');const [focusEnd,setFocusEnd]=useState('18:00');
  const [focus,setFocus]=useState<ReturnType<typeof focusWindow>|null>(null);
  const rgb=[1,3,5].map(i=>parseInt(background.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);
  const light=rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.179;
  const [settingsOpen,setSettingsOpen]=useState(false);const settingsDialog=useRef<HTMLDialogElement>(null);
  const [message,setMessage]=useState(''); const [full,setFull]=useState(false);const stage=useRef<HTMLDivElement>(null);
  const [keepAwake,setKeepAwake]=useState(false);const [awake,setAwake]=useState(false);
  const audio=useRef<AudioContext|null>(null);const first=useRef(true);const fired=useRef(new Set<string>());
  const elapsed=swTotal+(swStart===null?0:Math.max(0,now-swStart));const left=deadline===null?remaining:Math.max(0,deadline-now);
  const label=(zone:string)=>{const item=cityZones.find(c=>c[0]===zone);return item?item[['ko','en','ja','zh','es'].indexOf(language)+1]:zone.replace(/_/g,' ');};
  const time=(zone:string,showSeconds=seconds)=>new Intl.DateTimeFormat(locale,{timeZone:zone,hour:'2-digit',minute:'2-digit',...(showSeconds?{second:'2-digit'}:{}),hourCycle:h24?'h23':'h12'}).format(now);
  const date=(zone:string)=>new Intl.DateTimeFormat(locale,{timeZone:zone,month:'long',day:'numeric',weekday:'short'}).format(now);
  const offset=(zone:string)=>new Intl.DateTimeFormat('en',{timeZone:zone,timeZoneName:'shortOffset'}).formatToParts(now).find(p=>p.type==='timeZoneName')?.value;
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),100);const show=()=>setNow(Date.now());document.addEventListener('visibilitychange',show);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',show);};},[]);
  useEffect(()=>{try{localStorage.setItem('qk-clock-skin',JSON.stringify(skin));localStorage.setItem('qk-clock-background',JSON.stringify(background));localStorage.setItem('qk-clock-zones',JSON.stringify(zones));localStorage.setItem('qk-clock-main',JSON.stringify(main));localStorage.setItem('qk-clock-24',JSON.stringify(h24));localStorage.setItem('qk-clock-seconds',JSON.stringify(seconds));localStorage.setItem('qk-clock-alarms',JSON.stringify(alarms));}catch{}},[zones,main,h24,seconds,alarms,background,skin]);
  useEffect(()=>{const update=()=>setFull(document.fullscreenElement===stage.current);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
  useEffect(()=>{let lock:{release:()=>Promise<void>}|null=null;let cancelled=false;const acquire=async()=>{if(!keepAwake||document.visibilityState!=='visible')return;try{const api=(navigator as Navigator & {wakeLock?:{request:(kind:'screen')=>Promise<{release:()=>Promise<void>}>}}).wakeLock;if(!api)throw Error();const next=await api.request('screen');if(cancelled)await next.release();else{lock=next;setAwake(true);}}catch{if(!cancelled){setMessage(s.wakeFail);setKeepAwake(false);}}};void acquire();document.addEventListener('visibilitychange',acquire);return()=>{cancelled=true;void lock?.release();setAwake(false);document.removeEventListener('visibilitychange',acquire);};},[keepAwake,s.wakeFail]);
  useEffect(()=>()=>{void audio.current?.close();audio.current=null;},[]);
  useEffect(()=>{const dialog=settingsDialog.current;if(!dialog)return;if(settingsOpen&&!dialog.open)dialog.showModal();else if(!settingsOpen&&dialog.open)dialog.close();if(!settingsOpen)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;};},[settingsOpen]);
  useEffect(()=>{if(alerts.length)setSettingsOpen(false);},[alerts.length]);
  async function unlock(){try{if(!audio.current)audio.current=new AudioContext();if(audio.current.state!=='running')await audio.current.resume();}catch{setMessage(s.audioFail);}}
  function beep(kind:string){const ctx=audio.current;if(!ctx||ctx.state!=='running')return;for(let i=0;i<3;i++){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=kind==='bright'?'triangle':'sine';osc.frequency.value=kind==='bell'?1046:kind==='bright'?880:660;const at=ctx.currentTime+i*.3;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(.18,at+.02);gain.gain.exponentialRampToValueAtTime(.001,at+.23);osc.connect(gain);gain.connect(ctx.destination);osc.start(at);osc.stop(at+.25);}}
  useEffect(()=>{if(!alerts.length)return;beep(alerts[0].tone);const start=Date.now();const id=setInterval(()=>{if(Date.now()-start<60000)beep(alerts[0].tone);else clearInterval(id);},2000);return()=>clearInterval(id);},[alerts]);
  useEffect(()=>{if(first.current){first.current=false;return;}const due=alarms.filter(a=>a.enabled&&a.next<=now&&!fired.current.has(`${a.id}:${a.next}`));if(due.length){due.forEach(a=>fired.current.add(`${a.id}:${a.next}`));setAlerts(prev=>[...prev,...due.map(a=>({id:crypto.randomUUID(),name:a.name||s.alarm,tone:a.tone}))]);setAlarms(prev=>prev.map(a=>due.some(d=>d.id===a.id)?{...a,days:[],enabled:false}:a));}
    const snoozed=snoozes.filter(a=>a.at<=now);if(snoozed.length){setAlerts(prev=>[...prev,...snoozed]);setSnoozes(prev=>prev.filter(a=>a.at>now));}
    if(focus&&!focus.done&&now>=focus.end){track('tool_complete',{clock_mode:'focus'});setFocus({...focus,done:true});setAlerts(prev=>[...prev,{id:crypto.randomUUID(),name:s.focusDone,tone}]);}
    if(deadline!==null&&now>=deadline){track('tool_complete',{clock_mode:'timer'});setDeadline(null);setRemaining(0);setAlerts(prev=>[...prev,{id:crypto.randomUUID(),name:s.done,tone}]);}
  },[now,alarms,snoozes,deadline,focus,s.focusDone,s.alarm,s.done,tone]);
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await stage.current?.requestFullscreen();}catch{setMessage(s.fullFail);}}
  function addAlarm(){if(alarms.length>=12){setMessage(s.max);return;}void unlock();setAlarms(prev=>[...prev,{id:crypto.randomUUID(),name:alarmName.trim(),time:alarmTime,zone:alarmZone,days:[],tone,enabled:true,next:nextAlarm(alarmTime,alarmZone,[],Date.now())}]);setAlarmName('');}
  function snooze(min:number){if(!alerts[0])return;setSnoozes(prev=>[...prev,{...alerts[0],at:Date.now()+min*60000}]);setAlerts(prev=>prev.slice(1));}
  const upcoming=[...alarms.filter(a=>a.enabled).map(a=>({name:a.name||s.alarm,at:a.next})),...snoozes].sort((a,b)=>a.at-b.at)[0];
  const matching=cityZones.filter(c=>c.some(v=>v.toLowerCase().includes(search.toLowerCase()))&&!zones.includes(c[0]));
  return <div className="app-container world-page"><Header/><button className="btn-tool" onClick={()=>navigate('/')} style={{background:'var(--accent-light)',color:'var(--accent-color)'}}><ArrowLeft size={16}/>{t.backToHub.replace(/^\s*[←⇐⟵]\s*/, '')}</button>
    <div className="world-intro"><span className="badge">TIME STUDIO</span><h1>{s.title}</h1><p>{s.subtitle}</p></div>
    <AdSlot slotId="world-clock-top-banner" />
      <div ref={stage} className="world-stage" style={{background,'--world-ink':light?'#111827':'#f8fafc','--world-muted':light?'#27364a':'#cbd5e1'} as CSSProperties}><div className="world-stage-tools"><div className="world-tabs">{(['clock','stopwatch','timer','focus'] as const).map(v=><button key={v} aria-pressed={mode===v} onClick={()=>{if(v!==mode)track('clock_mode_change',{clock_mode:v,previous_mode:mode});setMode(v);}}>{s[v]}</button>)}</div><div className="world-row"><button className="world-settings-trigger" aria-haspopup="dialog" onClick={()=>setSettingsOpen(true)}><Settings size={18}/>{s.settings}</button><button onClick={()=>void fullscreen()} aria-label={full?s.exit:s.full}>{full?<Minimize size={20}/>:<Maximize size={20}/>}</button></div></div>
      <div className="world-face">{mode==='clock'&&<div className="world-eyebrow">{`${main===localZone?s.local+' · ':''}${label(main)}`}</div>}{mode==='clock'?<ClockFace skin={skin} now={Math.floor(now/1000)*1000} zone={main} locale={locale} h24={h24} seconds={seconds}/>:<DurationFace key={mode} skin={skin} value={mode==='stopwatch'?duration(elapsed,true):mode==='focus'?duration(focus?Math.ceil(Math.max(0,(now<focus.start?focus.start:focus.end)-now)/1000)*1000:0):duration(Math.ceil(left/1000)*1000)}/>}{(mode==='clock'||mode==='focus')&&<p>{mode==='clock'?`${date(main)} · ${offset(main)}`:!focus?s.focusEmpty:focus.done?s.focusDone:now<focus.start?s.waiting:s.focusing}</p>}
      {mode==='focus'&&focus&&<><p>{new Intl.DateTimeFormat(locale,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(focus.start)} → {new Intl.DateTimeFormat(locale,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(focus.end)} · {s.local}</p><progress aria-label={s.progress} max={100} value={Math.min(100,Math.max(0,(now-focus.start)/(focus.end-focus.start)*100))}/><div className="world-controls"><button onClick={()=>setFocus(null)}>{s.cancel}</button></div></>}
      {mode==='stopwatch'&&<div className="world-controls"><button onClick={()=>{track('tool_action',{clock_mode:'stopwatch',action:swStart===null?'start':'pause'});if(swStart===null)setSwStart(Date.now());else{setSwTotal(swTotal+Date.now()-swStart);setSwStart(null);}}}>{swStart!==null?s.pause:swTotal?s.resume:s.start}</button><button disabled={swStart===null||laps.length>=100} onClick={()=>setLaps(prev=>[...prev,elapsed].slice(-100))}>{s.lap}</button><button onClick={()=>{setSwStart(null);setSwTotal(0);setLaps([]);}}>{s.reset}</button></div>}
      {mode==='timer'&&<div className="world-controls"><button disabled={left<=0&&deadline===null} onClick={()=>{track('tool_action',{clock_mode:'timer',action:deadline===null?'start':'pause'});void unlock();if(deadline===null)setDeadline(Date.now()+remaining);else{setRemaining(Math.max(0,deadline-Date.now()));setDeadline(null);}}}>{deadline!==null?s.pause:left===minutes*60000?s.start:s.resume}</button><button onClick={()=>{setDeadline(null);setRemaining(minutes*60000);}}>{s.reset}</button></div>}
      {upcoming&&<small className="world-next">{s.next}: {upcoming.name} · {new Intl.DateTimeFormat(locale,{hour:'2-digit',minute:'2-digit'}).format(upcoming.at)} ({duration(upcoming.at-now)})</small>}</div>
      <div className="world-cities">{zones.map(zone=><div className={`world-city ${zone===main?'selected':''}`} key={zone}><button className="world-city-main" aria-label={`${s.main}: ${label(zone)} · ${isDaytime(now,zone)?s.day:s.night}`} onClick={()=>{setMain(zone);setMode('clock');}}><span className="world-city-heading"><span>{label(zone)}</span><span className={`world-daylight ${isDaytime(now,zone)?'is-day':'is-night'}`} title={`${isDaytime(now,zone)?s.day:s.night} · ${s.dayNightHelp}`} aria-hidden="true">{isDaytime(now,zone)?<Sun size={19}/>:<Moon size={19}/>}</span></span><strong>{time(zone,false)}</strong><small>{date(zone)} · {offset(zone)}</small></button><div className="world-city-actions"><button aria-label={`← ${label(zone)}`} disabled={zones.indexOf(zone)===0} onClick={()=>setZones(prev=>{const next=[...prev],i=next.indexOf(zone);[next[i-1],next[i]]=[next[i],next[i-1]];return next;})}>←</button><button disabled={zones.length<=1} aria-label={`${s.remove}: ${label(zone)}`} onClick={()=>{setZones(prev=>prev.filter(z=>z!==zone));if(main===zone)setMain(zones.find(z=>z!==zone)||localZone);}}><X size={13}/></button></div></div>)}</div>
<div className="world-background-bar"><label>{s.background}<input aria-label={s.background} type="color" value={background} onChange={e=>setBackground(e.target.value)}/></label><div className="world-swatches">{['#0d1423','#101010','#183d35','#392d55','#f5e9cf','#ffffff'].map(color=><button key={color} aria-label={`${s.background}: ${color}`} aria-pressed={background===color} style={{background:color}} onClick={()=>setBackground(color)}/>)}</div></div>
      {full&&<small className="world-full-hint">{s.controls}</small>}
      {alerts.length>0&&<div className="world-alert" role="alert"><Bell size={24}/><strong>{alerts[0].name}</strong><button onClick={()=>setAlerts(prev=>prev.slice(1))}>{s.stop}</button><button onClick={()=>snooze(5)}>{s.snooze} 5 {s.minute}</button><button onClick={()=>snooze(10)}>{s.snooze} 10 {s.minute}</button></div>}
      <dialog ref={settingsDialog} className="world-settings-dialog" aria-labelledby="world-settings-title" onCancel={e=>{e.preventDefault();setSettingsOpen(false);}} onClose={()=>setSettingsOpen(false)} onClick={e=>{if(e.target!==e.currentTarget)return;const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setSettingsOpen(false);}}>
        <div className="world-settings-header"><h2 id="world-settings-title">{s.settings}</h2><button autoFocus aria-label={s.closeSettings} onClick={()=>setSettingsOpen(false)}><X size={22}/></button></div>
        <div className="world-settings-body">{message&&<p role="status" className="world-message">{message}<button onClick={()=>setMessage('')}>×</button></p>}
    <fieldset className="clock-skin-options"><legend>{s.skin}</legend><div className="clock-skin-grid">{clockSkins.map(option=><label className="clock-skin-card" key={option}><span className="clock-skin-preview"><ClockDisplay skin={option} groups={['12','48']}/></span><span className="clock-skin-caption"><input type="radio" name="clock-skin" value={option} checked={skin===option} onChange={()=>setSkin(option)}/>{s.skins[option]}</span></label>)}</div></fieldset>
    <div className="world-options"><label><input type="checkbox" checked={h24} onChange={e=>setH24(e.target.checked)}/>{s.format}</label><label><input type="checkbox" checked={seconds} onChange={e=>setSeconds(e.target.checked)}/>{s.seconds}</label><label><input type="checkbox" checked={keepAwake} onChange={e=>setKeepAwake(e.target.checked)}/>{s.wake}{awake?' ✓':''}</label></div>
    <div className="world-panels"><section className="glass-card world-panel"><h2>{s.city}</h2><input aria-label={s.search} placeholder={s.search} value={search} onChange={e=>{setSearch(e.target.value);const hit=cityZones.find(c=>c.some(v=>v.toLowerCase().includes(e.target.value.toLowerCase()))&&!zones.includes(c[0]));if(hit)setChoice(hit[0]);}}/><div className="world-row"><select aria-label={s.city} value={matching.some(c=>c[0]===choice)?choice:matching[0]?.[0]||''} onChange={e=>setChoice(e.target.value)}>{matching.map(c=><option key={c[0]} value={c[0]}>{label(c[0])} · {c[0]}</option>)}</select><button disabled={!matching.length||zones.length>=8} onClick={()=>{const zone=matching.some(c=>c[0]===choice)?choice:matching[0]?.[0];if(zone)setZones(prev=>[...prev,zone]);}}>{s.add}</button></div>
    <h2>{s.focus}</h2><p className="world-notice">{s.focusHelp}</p><form onSubmit={e=>{e.preventDefault();try{const session=focusWindow(focusDate,focusStart,focusEnd);if(session.end<=Date.now())throw Error();void unlock();track('tool_action',{clock_mode:'focus',action:'schedule'});setFocus(session);setMode('focus');setMessage('');setSettingsOpen(false);}catch{setMessage(s.focusInvalid);}}}><label>{s.focusDate}<input type="date" required value={focusDate} onChange={e=>setFocusDate(e.target.value)}/></label><div className="world-row"><label>{s.from}<input type="time" required value={focusStart} onChange={e=>setFocusStart(e.target.value)}/></label><label>{s.until}<input type="time" required value={focusEnd} onChange={e=>setFocusEnd(e.target.value)}/></label></div><button className="world-primary" type="submit">{s.schedule}</button></form>
    <h2>{s.timer}</h2><label>{s.duration}<input type="number" min="1" max="1440" value={minutes} disabled={deadline!==null} onChange={e=>{const n=Math.max(1,Math.min(1440,Number(e.target.value)||1));setMinutes(n);setRemaining(n*60000);}}/></label><div className="world-row">{[5,10,25,60].map(n=><button key={n} disabled={deadline!==null} onClick={()=>{setMinutes(n);setRemaining(n*60000);setMode('timer');}}>{n} {s.minute}</button>)}</div>
    <h2>{s.lap}</h2><button disabled={!laps.length} onClick={()=>{void (navigator.clipboard ? navigator.clipboard.writeText(laps.map((v,i)=>`${i+1}\t${duration(v,true)}\t+${duration(v-(laps[i-1]||0),true)}`).join('\n')) : Promise.reject()).then(()=>setMessage(s.copied),()=>setMessage(s.copyFail));}}>{s.copy}</button><div className="world-laps">{laps.length?<ol>{laps.map((v,i)=><li key={i}><span>{i+1}</span><strong>{duration(v,true)}</strong><small>+{duration(v-(laps[i-1]||0),true)}</small></li>)}</ol>:<p>{s.emptyLaps}</p>}</div></section>
    <section className="glass-card world-panel"><h2>{s.alarm}</h2><p className="world-notice">{s.notice}</p><form onSubmit={e=>{e.preventDefault();addAlarm();}}><label>{s.name}<input maxLength={60} value={alarmName} onChange={e=>setAlarmName(e.target.value)}/></label><div className="world-row"><label>{s.time}<input type="time" required value={alarmTime} onChange={e=>setAlarmTime(e.target.value)}/></label><label>{s.zone}<select value={alarmZone} onChange={e=>setAlarmZone(e.target.value)}>{Array.from(new Set([localZone,...cityZones.map(c=>c[0])])).map(z=><option key={z} value={z}>{z===localZone?s.local+' · ':''}{label(z)}</option>)}</select></label></div><label>{s.sound}<select value={tone} onChange={e=>setTone(e.target.value)}><option value="soft">{s.soft}</option><option value="bright">{s.bright}</option><option value="bell">{s.bell}</option></select></label><div className="world-row"><button type="button" onClick={()=>void unlock().then(()=>beep(tone))}>{s.test}</button><button type="submit" className="world-primary">{s.save}</button></div></form><div className="world-alarm-list">{!alarms.length&&<p>{s.none}</p>}{alarms.map(a=><div key={a.id}><label><input type="checkbox" aria-label={`${s.enabled}: ${a.name||a.time}`} checked={a.enabled} onChange={e=>setAlarms(prev=>prev.map(v=>v.id===a.id?{...v,enabled:e.target.checked,next:nextAlarm(v.time,v.zone,[],Date.now())}:v))}/><strong>{a.time}</strong> {a.name}</label><small>{label(a.zone)} · {s.once}</small><button aria-label={`${s.remove}: ${a.name||a.time}`} onClick={()=>setAlarms(prev=>prev.filter(v=>v.id!==a.id))}><X size={16}/></button></div>)}</div></section></div>
        </div>
      </dialog>
    </div>
    {message&&!settingsOpen&&<p role="status" className="world-message">{message}<button onClick={()=>setMessage('')}>×</button></p>}
    <AdSlot slotId="world-clock-bottom-banner" />
      <section className="glass-card world-panel world-help" aria-labelledby="world-guide-title"><h2 id="world-guide-title">{s.help}</h2><div className="world-guide-grid">{guide.sections.map((item,i)=><section key={i}><h3>{i+1}. {item.title}</h3><p>{item.body}</p></section>)}</div></section>
  </div>;
}
