const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict');
const m={};new Function('exports',ts.transpileModule(fs.readFileSync('src/features/units/model.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText)(m);
const eq=(a,b)=>assert(Math.abs(a-b)<=Math.max(Math.abs(b)*1e-10,1e-12),`${a} != ${b}`);
eq(m.convert(1,'length','in','cm'),2.54);eq(m.convert(1,'mass','lb','kg'),.45359237);eq(m.convert(1,'area','pyeong','m2'),400/121);eq(m.convert(1,'volume','gal-us','ml'),3785.411784);eq(m.convert(1,'volume','gal-uk','ml'),4546.09);eq(m.convert(32,'temperature','f','c'),0);eq(m.convert(-40,'temperature','c','f'),-40);eq(m.convert(0,'temperature','k','c'),-273.15);assert.throws(()=>m.convert(-1,'temperature','k','c'));eq(m.convert(1,'speed','mph','ms'),.44704);eq(m.convert(1,'time','week','hr'),168);eq(m.convert(1,'data','GiB','B'),1073741824);eq(m.convert(1,'data','GB','B'),1e9);eq(m.convert(1,'data','B','bit'),8);eq(m.convert(1,'pressure','atm','pa'),101325);eq(m.convert(1,'energy','kwh','j'),3600000);eq(m.convert(1,'power','ps','w'),735.49875);eq(m.convert(180,'angle','deg','rad'),Math.PI);eq(m.convert(1,'cooking','cup-us','g','flour'),120);eq(m.convert(120,'cooking','g','cup-us','flour'),1);eq(m.convert(1,'cooking','cup-200','ml'),200);assert(m.convert(1e-15,'length','m','cm')>0);assert.throws(()=>m.convert(1e308,'length','km','mm'));
for(const c of m.categories){assert.equal(c.names.length,5);for(const u of c.units){assert.equal(u.names.length,5);for(const v of c.units){const n=c.id==='temperature'?300:12.345;eq(m.convert(m.convert(n,c.id,u.id,v.id),c.id,v.id,u.id),n);}}for(const region of m.regions){const p=m.preferred(c.id,region);assert(p.length>=2);assert(p.every(id=>c.units.some(u=>u.id===id)));}}
assert.equal(m.defaultRegion('en','en-GB'),'GB');assert.equal(m.defaultRegion('zh','zh-TW'),'TW');assert.equal(m.defaultRegion('ko','en-US'),'KR');assert.equal(m.parseNumber('1,234.5','en-US'),1234.5);assert.equal(m.parseNumber('1.234,5','es-ES'),1234.5);assert.equal(m.parseNumber('1,5','es-ES'),1.5);assert(Number.isNaN(m.parseNumber('1,5','en-US')));assert.equal(m.parseNumber('','ko-KR'),null);assert(!m.validSelection({category:'length',from:'kg',to:'m',ingredient:'water'}));
console.log('PASS: 13 categories, all pair roundtrips, tiny/overflow/absolute-zero boundaries, cooking, regional defaults, five-language coverage and localized number parsing.');
assert.equal(m.exactUnit('센티미터').unit.id,'cm');assert.equal(m.exactUnit('centimeter').unit.id,'cm');assert.equal(m.exactUnit('センチメートル').unit.id,'cm');assert.equal(m.exactUnit('厘米').unit.id,'cm');assert.equal(m.exactUnit('centímetro').unit.id,'cm');assert.equal(m.exactUnit('mL'),null);assert(m.searchUnits('gal').length>=2);assert.equal(m.searchUnits('no_such_unit').length,0);assert.equal(m.searchUnits('').length,0);
const texts={};new Function('exports',ts.transpileModule(fs.readFileSync('src/features/units/text.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(texts);for(const [key,values] of Object.entries(texts.copy)){assert.equal(values.length,5,key);assert(values.every(s=>typeof s==='string'&&s.trim()),key);}
console.log('PASS: multilingual search, ambiguous units, empty results and all UI translations.');
